apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-ausf-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |    
    logger:
        file: /var/log/open5gs/ausf.log
    
    ausf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
