apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-ausf-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |    
    logger:
        file: /var/log/open5gs/ausf.log
    
    ausf:
      sbi:
        - dev: eth0
          port: 7777
    
    nrf:
      sbi:
        - name: "{{ .Release.Namespace }}-nrf-svc-pool"
          port: 7777
