apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-pcf-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: pcf
data:
  pcf.yaml: |
    db_uri: {{ .Values.db_uri }}
    
    logger:
        file: /var/log/open5gs/pcf.log
    
    pcf:
      sbi:
        - dev: eth0
          port: 7777
    nrf:
      sbi:
        - name: "{{ .Release.Namespace }}-nrf-svc-pool"
          port: 7777
