{{ if eq .Values.network_4g true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-mme-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: mme
data:
  mme.yaml: |
    logger:
        file: /var/log/open5gs/mme.log
    
    parameter:
    
    mme:
        freeDiameter: /open5gs/config-map/diameter-mme.conf
        s1ap:
           dev: eth0        
        gtpc:
           dev: eth0        
        gummei:
          plmn_id:
            mcc: 001
            mnc: 01
          mme_gid: 2
          mme_code: 1
        tai:
          plmn_id:
            mcc: 001
            mnc: 01
          tac: 7
        security:
            integrity_order : [ EIA1, EIA2, EIA0 ]
            ciphering_order : [ EEA0, EEA1, EEA2 ]
        network_name:
            full: Open5GS
        mme_name: open5gs-mme0
    
    sgwc:
        gtpc:
          - name: "open5gs-sgwc-svc-pool"
    
    smf:
        gtpc:
          - name: "open5gs-pgwc-svc-pool"
{{ end }}