apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-pgwc-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: pgwc
data:
  pgwc.yaml: |
    logger:
        file: /var/log/open5gs/pgwc.log
    
    smf:
      sbi:
        - dev: eth0
          port: 7777
      pfcp:
          dev: eth0
      gtpc:
          dev: eth0
      gtpu:
          dev: eth0
      subnet:
        - addr: 10.45.0.1/16
          dnn: internet
        - addr: cafe::1/64
          dnn: internet
      dns:
        - 8.8.8.8
        - 8.8.4.4
        - 2001:4860:4860::8888
        - 2001:4860:4860::8844
      mtu: 1400
    
    upf:
      pfcp:
        - name: "{{ .Release.Namespace }}-pgwu-svc-pool"
    nrf:
      sbi:
        - name: "{{ .Release.Namespace }}-nrf-svc-pool"
          port: 7777
