apiVersion: v1
kind: Service
metadata:
  name: open5gs-hss-svc-pool
  namespace: open5gs
  labels:
    epc-mode: hss
spec:
  ports:
  - name: s6a
    port: 3868
    protocol: TCP
  selector:
    epc-mode: hss
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: open5gs-hss-deployment
  namespace: open5gs
  labels:
    epc-mode: hss
spec:
  replicas: 1 
  serviceName: "open5gs-hss-svc-pool"
  selector:
    matchLabels:
      epc-mode: hss
  template:
    metadata:
     labels:
        epc-mode: hss
        level: pod
    spec:
      containers:
        - name: hss
          image: open5gs-custom
          imagePullPolicy: Never
          command: ["open5gs-hssd", "-c", "/open5gs/config-map/hss.yaml"]
          volumeMounts:
          - name: open5gs-hss-config
            mountPath: /open5gs/config-map/hss.yaml
            subPath: "hss.yaml"
          - name: open5gs-hss-diameter
            mountPath: /open5gs/config-map/diameter-hss.conf
            subPath: "diameter-hss.conf"            
      volumes:
      - name: open5gs-hss-config
        configMap:
          name: open5gs-hss-config
      - name: open5gs-hss-diameter
        configMap:
          name: open5gs-hss-diameter          
