{{ if eq .Values.network_4g true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-pcrf-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: pcrf
data:
  pcrf.yaml: |
    db_uri: mongodb://mongodb/open5gs?replicaSet=rs0
    
    logger:
        file: /var/log/open5gs/pcrf.log
    
    parameter:
    
    pcrf:
        freeDiameter: /open5gs/config-map/diameter-pcrf.conf
{{ end }}
