apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-nssf-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: nssf
data:
  nssf.yaml: |    
    logger:
        file: /var/log/open5gs/nssf.log
    
    nssf:
      sbi:
        - dev: eth0
          port: 7777
      nsi:
        - name: "{{ .Release.Namespace }}-nrf-svc-pool"
          port: 7777
          s_nssai:
            sst: 1
    nrf:
      sbi:
        - name: "{{ .Release.Namespace }}-nrf-svc-pool"
          port: 7777