apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-nssf-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: nssf
data:
  nssf.yaml: |    
    logger:
        file: /var/log/open5gs/nssf.log
    
    nssf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
      nsi:
        - addr: ::1
          port: 7777
          s_nssai:
            sst: 1
