apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-amf-svc-pool-external
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: amf
spec:
  selector:
    epc-mode: amf    
  type: LoadBalancer
  externalIPs:
    - {{ .Values.mmeExternalAddress }}
  ports:
  - name: n2
    port: 38412
    targetPort: 38412
    protocol: SCTP  
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ .Release.Namespace }}-amf-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: amf
spec:
  replicas: 1
  serviceName: "{{ .Release.Namespace }}-amf-svc-pool"
  selector:
    matchLabels:
      epc-mode: amf
  template:
    metadata:
      labels:
        epc-mode: amf
    spec:
      containers:
        - name: amf
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["open5gs-amfd", "-c", "/open5gs/config-map/amf.yaml"]
          volumeMounts:
          - name: {{ .Release.Namespace }}-amf-config
            mountPath: /open5gs/config-map/amf.yaml
            subPath: "amf.yaml"         
          ports:
            - name: n2 
              containerPort: 36412
              protocol: SCTP
            - name: sbi
              containerPort: 80
              protocol: TCP
      nodeSelector:
        mobile-core: cp
      volumes:
        - name: {{ .Release.Namespace }}-amf-config
          configMap:
            name: {{ .Release.Namespace }}-amf-config
