apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-amf-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: amf
data:
  amf.yaml: |
    logger:
        file: /var/log/open5gs/amf.log    
    amf:
        sbi:
          - dev: eth0
            port: 7777
        ngap:
           dev: eth0
        guami:
          - plmn_id:
              mcc: 001
              mnc: 01
            amf_id:
              region: 2
              set: 1
        tai:
          - plmn_id:
              mcc: 001
              mnc: 01
            tac: 7
        plmn_support:
          - plmn_id:
              mcc: 001
              mnc: 01
            s_nssai:
              - sst: 1
        tai:
          plmn_id:
            mcc: 001
            mnc: 01
        security:
            integrity_order : [ NIA2, NIA1, NIA0 ]
            ciphering_order : [ NEA0, NEA1, NEA2 ]
        network_name:
            full: Open5GS
        amf_name: open5gs-amf0
    nrf:
      sbi:
        - name: "{{ .Release.Namespace }}-nrf-svc-pool"
          port: 7777
