apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pgwc-config
  namespace: open5gs
  labels:
    epc-mode: pgwc
data:
  pgwc.yaml: |
    logger:
        file: /var/log/open5gs/pgwc.log
    
    parameter:
    
    smf:
        freeDiameter: /open5gs/config-map/diameter-pgwc.conf
        gtpc:
           dev: eth0
        pfcp:
           dev: eth0
        pdn:
          - addr: 10.45.0.1/16
          - addr: cafe::1/64
        dns:
          - 8.8.8.8
          - 8.8.4.4
          - 2001:4860:4860::8888
          - 2001:4860:4860::8844
        mtu: 1400
    
    upf:
        pfcp:
          - name: "open5gs-pgwu-svc-pool"
