apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-udr-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: udr
data:
  udr.yaml: |
    db_uri: {{ .Values.db_uri }}
    
    logger:
        file: /var/log/open5gs/udr.log
    
    udr:
      sbi:
        - dev: eth0
          port: 7777
    nrf:
      sbi:
        - name: "{{ .Release.Namespace }}-nrf-svc-pool"
          port: 7777