apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-udm-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: udm
data:
  udm.yaml: |    
    logger:
        file: /var/log/open5gs/udm.log
    
    udm:
      sbi:
        - addr: 0.0.0.0
          port: 7777
