apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-udm-svc-pool
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: udm
spec:
  selector:
    epc-mode: udm
  ports:
  - name: sbi
    port: 7777
    protocol: TCP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ .Release.Namespace }}-udm-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: udm
spec:
  replicas: 1
  serviceName: "{{ .Release.Namespace }}-udm-svc-pool"
  selector:
    matchLabels:
      epc-mode: udm
  template:
    metadata:
      labels:
        epc-mode: udm
    spec:
      containers:
        - name: udm
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["open5gs-udmd", "-c", "/open5gs/config-map/udm.yaml"]
          volumeMounts:
          - name: {{ .Release.Namespace }}-udm-config
            mountPath: /open5gs/config-map/udm.yaml
            subPath: "udm.yaml"
          {{ if eq .Values.requestsPreferences.udm.requestsLimitsDefinition true}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{ end }}
          ports:
            - name: sbi
              containerPort: 7777
              protocol: TCP 
      nodeSelector:
        mobile-core: cp
      volumes:
        - name: {{ .Release.Namespace }}-udm-config
          configMap:
            name: {{ .Release.Namespace }}-udm-config
