{{ if eq .Values.network_4g true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-hss-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: hss
data:
  hss.yaml: |
    db_uri: mongodb://mongodb/open5gs?replicaSet=rs0
    
    logger:
        file: /var/log/open5gs/hss.log
    
    parameter:
    
    hss:
        freeDiameter: /open5gs/config-map/diameter-hss.conf
{{ end }}