apiVersion: v1
kind: Service
metadata:
  name: srsenb-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: srsenb
spec:
  selector:
    app: srsenb
  ports:
  - name: nginxport
    port: 8080
    targetPort: 8080
    protocol: TCP
