apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-bsf-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: bsf
data:
  bsf.yaml: |
    db_uri: {{ .Values.db_uri }}
    
    logger:
        file: /var/log/open5gs/bsf.log
    
    bsf:
      sbi:
        - dev: eth0
          port: 7777
    nrf:
      sbi:
        - name: "{{ .Release.Namespace }}-nrf-svc-pool"
          port: 7777
