apiVersion: v1
kind: Service
metadata:
  name: open5gs-sgwu-svc-pool-external
  namespace: open5gs
  labels:
    epc-mode: sgwu
spec:
  type: LoadBalancer
  externalIPs:
    - 1.2.3.4
  ports:
    - name: s1u
      port: 2152
      targetPort: 2152
      protocol: UDP
  selector:
    epc-mode: sgwu
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-sgwu-svc-pool
  namespace: open5gs
  labels:
    epc-mode: sgwu
spec:
  clusterIP: None
  ports:
    - name: pfcp
      port: 8805
      protocol: UDP
  selector:
    epc-mode: sgwu        
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: open5gs-sgwu-deployment
  namespace: open5gs
  labels:
    epc-mode: sgwu
spec:
  replicas: 1
  serviceName: "open5gs-sgwu-svc-pool"
  selector:
    matchLabels:
      epc-mode: sgwu
  template:
    metadata:
      labels:
        epc-mode: sgwu
    spec:
      containers:
        - name: sgwu
          image: open5gs-custom
          imagePullPolicy: Never
          command: ["open5gs-sgwud", "-c", "/open5gs/config-map/sgwu.yaml"]
          volumeMounts:
            - name: open5gs-sgwu-config
              mountPath: /open5gs/config-map/sgwu.yaml
              subPath: "sgwu.yaml"
          ports:
            - name: gtpu
              containerPort: 2152 
              protocol: UDP
            - name: pfcp
              containerPort: 8805
              protocol: UDP
      volumes:
        - name: open5gs-sgwu-config
          configMap:
            name: open5gs-sgwu-config
