mmeExternalAddress: 1.2.3.4
sgwuExternalAddress: 1.2.3.4
webUiExternalAddress: 1.2.3.4
webUiPort: 80
initSubcribers: true
mongoReplicas: 1

requestsPreferences:
  hssDatabase:
    requestsLimitsDefinition: false
  hss:
    requestsLimitsDefinition: false
  pcrf:
    requestsLimitsDefinition: false
  mme:
    requestsLimitsDefinition: false
  sgwc:
    requestsLimitsDefinition: false
  sgwu:
    requestsLimitsDefinition: false
  pgwc:
    requestsLimitsDefinition: false
  pgwu:
    requestsLimitsDefinition: false

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "100Mi"
    cpu: "300m"

image:
  repository: naposto/open5gs-custom
  pullPolicy: IfNotPresent
  tag: latest

webUiImage:
  repository: naposto/open5gs-webui
  pullPolicy: IfNotPresent
  tag: latest