mmeExternalAddress: 1.2.3.4
sgwuExternalAddress: 1.2.3.4
webUiExternalAddress: 1.2.3.4
webUiPort: 80
initSubcribers: false
mongoReplicas: 1

requestsPreferences:
  hssDatabase:
    requestsLimitsDefinition: true
  hss:
    requestsLimitsDefinition: true
  pcrf:
    requestsLimitsDefinition: true
  mme:
    requestsLimitsDefinition: true
  sgwc:
    requestsLimitsDefinition: true
  sgwu:
    requestsLimitsDefinition: true
  pgwc:
    requestsLimitsDefinition: true
  pgwu:
    requestsLimitsDefinition: true

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "250Mi"
    cpu: "500m"

image:
  repository: open5gs-custom
  pullPolicy: IfNotPresent
  tag: latest

webUiImage:
  repository: open5gs-webui
  pullPolicy: IfNotPresent
  tag: latest