mmeExternalAddress: 172.16.4.239
sgwuExternalAddress: 172.16.4.235
webUiExternalAddress: 172.16.4.239
upfExternalAddress: 172.16.4.235
webUiPort: 80
initSubcribers: true
mongoReplicas: 1
network_4g: false


requestsPreferences:
  hssDatabase:
    requestsLimitsDefinition: false
  hss:
    requestsLimitsDefinition: false
  pcrf:
    requestsLimitsDefinition: false
  mme:
    requestsLimitsDefinition: false
  sgwc:
    requestsLimitsDefinition: false
  sgwu:
    requestsLimitsDefinition: false
  pgwc:
    requestsLimitsDefinition: false
  pgwu:
    requestsLimitsDefinition: false

interval: 5s

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "100Mi"
    cpu: "300m"

image:
  repository: naposto/ogs-2.4.8
  pullPolicy: IfNotPresent
  tag: latest

webUiImage:
  repository: naposto/ogs-webui-2.4.8
  pullPolicy: IfNotPresent
  tag: latest
