apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-sgwc-config
  namespace: open5gs
  labels:
    epc-mode: sgwc
data:
  sgwc.yaml: |
    logger:
        file: /var/log/open5gs/sgwc.log
        
    sgwc:
        gtpc:
           dev: eth0
        pfcp:
           dev: eth0

    sgwu:
        pfcp:
          - name: "open5gs-sgwu-svc-pool"        
