apiVersion: v1
kind: Service
metadata:
  name: open5gs-sgwc-svc-pool
  namespace: open5gs
  labels:
    epc-mode: sgwc
spec:
  clusterIP: None
  selector:
    epc-mode: sgwc        
  ports:
    - name: gtpc
      port: 2123
      protocol: UDP
    - name: pfcp
      port: 8805
      protocol: UDP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: open5gs-sgwc-deployment
  namespace: open5gs
  labels:
    epc-mode: sgwc
spec:
  replicas: 1
  serviceName: "open5gs-sgwc-svc-pool"
  selector:
    matchLabels:
      epc-mode: sgwc
  template:
    metadata:
      labels:
        epc-mode: sgwc
    spec:
      containers:
        - name: sgwc
          image: open5gs-custom
          imagePullPolicy: Never
          command: ["open5gs-sgwcd", "-c", "/open5gs/config-map/sgwc.yaml"]
          volumeMounts:
            - name: open5gs-sgwc-config
              mountPath: /open5gs/config-map/sgwc.yaml
              subPath: "sgwc.yaml"
          ports:
            - name: gtpc
              containerPort: 2123 
              protocol: UDP
            - name: pfcp
              containerPort: 8805
              protocol: UDP
      volumes:
        - name: open5gs-sgwc-config
          configMap:
            name: open5gs-sgwc-config
