apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-exporter
  namespace: {{ .Release.Namespace }}  
  labels:
    app: srsenb
spec:
  replicas: 1
  selector:
    matchLabels:
      srsenb: {{ .Release.Name }}-exporter
  template:
    metadata:
      labels:
        srsenb: {{ .Release.Name }}-exporter
        app: srsenb
    spec:
      containers:
      - name: {{ .Release.Name }}-nginx
        imagePullPolicy: IfNotPresent
        image: nginx
        volumeMounts:
        - name: {{ .Release.Name }}-nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: "nginx.conf"
      nodeSelector:
        mobile-core: cp        
      volumes:
      - name: {{ .Release.Name }}-nginx-config
        configMap:
          name: {{ .Release.Name }}-nginx-config