apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-nrf-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: nrf
data:
  nrf.yaml: |
    db_uri: {{ .Values.db_uri }}
    
    logger:
        file: /var/log/open5gs/nrf.log
    
    nrf:
      sbi:
        - dev: eth0
          port: 7777
