apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-nrf-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: nrf
data:
  nrf.yaml: |
    db_uri: mongodb://mongodb/open5gs?replicaSet=rs0
    
    logger:
        file: /var/log/open5gs/nrf.log
    
    nrf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
