apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcrf-config
  namespace: open5gs
  labels:
    epc-mode: pcrf
data:
  pcrf.yaml: |
    db_uri: mongodb://mongodb/open5gs?replicaSet=rs0
    
    logger:
        file: /var/log/open5gs/pcrf.log
    
    parameter:
    
    pcrf:
        freeDiameter: /open5gs/config-map/diameter-pcrf.conf
