apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-sgwc-config
  namespace: {{ .Release.Namespace }}
  labels:
    epc-mode: sgwc
data:
  sgwc.yaml: |
    logger:
        file: /var/log/open5gs/sgwc.log
        
    sgwc:
        gtpc:
           dev: eth0
        pfcp:
           dev: eth0

    sgwu:
        pfcp:
          - name: "{{ .Release.Namespace }}-sgwu-svc-pool"        
