apiVersion: v1
kind: Service
metadata:
  name: open5gs-mme-svc-pool-external
  namespace: open5gs
  labels:
    epc-mode: mme
spec:
  selector:
    epc-mode: mme    
  type: LoadBalancer
  externalIPs:
    - 1.2.3.4
  ports:
  - name: s1ap
    port: 36412
    targetPort: 36412
    protocol: SCTP  
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-mme-svc-pool
  namespace: open5gs
  labels:
    epc-mode: mme
spec:
  selector:
    app: appname
  type: ClusterIP
  ports:
  - name: s6a
    port: 3868
    protocol: TCP
  - name: gtpc
    port: 2123
    protocol: TCP

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: open5gs-mme-deployment
  namespace: open5gs
  labels:
    epc-mode: mme
spec:
  replicas: 1
  serviceName: "open5gs-mme-svc-pool"
  selector:
    matchLabels:
      epc-mode: mme
  template:
    metadata:
      labels:
        epc-mode: mme
    spec:
      containers:
        - name: mme
          image: open5gs-custom
          imagePullPolicy: Never
          command: ["open5gs-mmed", "-c", "/open5gs/config-map/mme.yaml"]
          volumeMounts:
          - name: open5gs-mme-config
            mountPath: /open5gs/config-map/mme.yaml
            subPath: "mme.yaml"
          - name: open5gs-mme-diameter
            mountPath: /open5gs/config-map/diameter-mme.conf
            subPath: "diameter-mme.conf"             
          ports:
            - name: s1ap 
              containerPort: 36412
              protocol: SCTP
            - name: s6a
              containerPort: 3868
              protocol: TCP
            - name: gtpc
              containerPort: 2123
              protocol: UDP                        
      volumes:
        - name: open5gs-mme-config
          configMap:
            name: open5gs-mme-config
        - name: open5gs-mme-diameter
          configMap:
            name: open5gs-mme-diameter
