apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pgwu-config
  namespace: open5gs
  labels:
    epc-mode: pgwu
data:
  pgwu.yaml: |
    logger:
        file: /var/log/open5gs/pgwu.log
    
    parameter:
    
    upf:
        pfcp:
           dev: eth0
        gtpu:
           dev: eth0
        pdn:
          - addr: 10.45.0.1/16
          - addr: cafe::1/64
